PickNikRobotics/moveit_pro_example_ws

src/lab_sim/config/config.yaml
src/lab_sim/objectives/pick_and_place_example.xml

Add an example Objective that utilizes the custom MTC behaviors developed in `example_behaviors`.

Add pick and place example using custom MTC example behavior

---

src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/00_solution_-_move_to_initial_pose.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/01_solution_-_create_a_pose.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/02_solution_-_visualize_a_pose.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/03_solution_-_pose_2m_above_the_robot.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/05_solution_-_define_a_path.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/06_solution_-_visualize_a_path.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/07_solution_-_plan_motion_for_a_path.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/08_solution_-_execute_path_plan.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/09_solution_-_an_infeasible_path.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/10_solution_-_visualize_path_error.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/12_solution_-_constrain_orientation.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/13_solution_-_load_a_path_from_file.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/15_solution_-_a_path_that_collides.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/16_solution_-_checking_for_collisions.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/17_solution_-_execute_the_feasible_path.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/18_solution_-_define_a_coverage_path.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/19_solution_-_execute_coverage_path.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/20_solution_-_look_at_the_airfoil.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/21_solution_-_find_the_airfoil.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/22_solution_-_visualize_airfoil_frame.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/23_solution_-_airfoil_coverage_origin.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/24_solution_-_airfoil_coverage_path.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/25_solution_-_execute_airfoil_coverage.xml
src/moveit_pro_mobile_manipulation/mobile_manipulation_config/objectives/take_snapshot.xml

Closes https://github.com/PickNikRobotics/moveit_studio/issues/9619

mobile_manipulation_config: revisit favorites

---

src/moveit_pro_kinova_configs/kinova_gen3_base_config/package.xml
src/moveit_pro_kinova_configs/kinova_gen3_mujoco_config/description/picknik_kinova_gen3.xacro

The kinova_description installed via rosdep only has STL files, our external dependency in the kortex_ws points to a repo with only DAE, and the current `main` has both.
I'm wondering if there are any changes missing from the `rosdep` installed version we need or if we can install the `kortex_description` package without source building it

added dependency

---

src/moveit_pro_ur_configs/bring_it_sim/description/ur5e_ridgeback.xacro
src/moveit_pro_ur_configs/bring_it_sim/launch/agent_bridge.launch.xml

Fix typo "virtual_rail"
Re-add the agent launch file

Bring it updates

---

src/moveit_pro_kinova_configs/kinova_gen3_base_config/package.xml

This should also keep us from pulling the moveit_core, moveit_msgs, and moveit_common binaries with rosdep

Remove unused pick_ik dependency

---

src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/request_teleoperation.xml

This PR stops joint jog from hanging when the race condition described in https://github.com/PickNikRobotics/moveit_studio/issues/9828 occurs simply by setting a timeout in a RetrieveJointStateParameter behavior. 
The race condition can still occur but the timeout prevents it from happening repeatedly.
Add a delay to the changed RetrieveJointStateParameter behavior like shown to repro the race condition reliably.
Then after switching from 'Waypoints' to 'Joint Jog' teleop modes, and manipulating a joint, you'll see an error from RetrieveJointStateParameter for timing out. Continuing to manipulate joints should then work.

Keep joint jog jogging instead of hanging

---

src/lab_sim/objectives/create_pose_vector.xml

`PlanMTC` has significantly reduced performance when called with multiple `SetupMTCMoveToPose` stages and can no longer plan for as many poses. Reducing the number of poses as a quick fix enables the `PlanAndSaveTrajectory` objective to work again.

Reduce the poses used in PlanAndSaveTrajectory

---

Dockerfile
docker-compose.yaml

It seems that on my machine the instructions do not enable GPU support. Following them (uncommenting the `docker-compose.yaml` lines and `moveit_pro build`ing) I am unable to run `nvidia-smi` inside the container and no GPUs are found, but I do see the stage in which the nvidia drivers are installed when the image is built. If I leave the docker-compose file as it in in this PR (with the lines uncommented), I don't have to build anything differently and I can run `nvidia-smi` or `nvtop` and see my GPU is in use

Update docker compose for GPU

---

src/lab_sim/waypoints/ur_waypoints.yaml

It is used by "3 Waypoints Pick and Place" but was removed accidetally in an earlier change
Running "3 Waypoints Pick and Place" is sufficient to test this

Add Pick Cube waypoint

---

src/moveit_pro_kinova_configs/kinova_gen3_base_config/objectives/move_along_path.xml
src/moveit_pro_kinova_configs/kinova_gen3_base_config/objectives/request_teleoperation.xml
src/moveit_pro_kinova_configs/kinova_gen3_mujoco_config/objectives/april_tag_object_registration.xml
src/moveit_pro_kinova_configs/kinova_gen3_mujoco_config/objectives/compliant_grasp_rafti.xml
src/moveit_pro_kinova_configs/kinova_gen3_mujoco_config/objectives/compliant_grasp_rafti_vfc.xml
src/moveit_pro_kinova_configs/kinova_gen3_mujoco_config/objectives/move_along_path.xml
src/moveit_pro_kinova_configs/kinova_gen3_mujoco_config/objectives/request_teleoperation.xml

Fix up a few broken objectives I found in the kinova configs

Update kinova objectives

---

src/lab_sim/objectives/constrained_pick_and_place_subtree.xml
src/moveit_pro_kinova_configs/kinova_gen3_mujoco_config/objectives/constrained_pick_place.xml
src/moveit_pro_ur_configs/arm_on_rail_sim/objectives/constrained_pick_place.xml
src/moveit_pro_ur_configs/picknik_ur_mock_hw_config/objectives/constrained_pick_place.xml

This PR removes all the `RetryUntilSuccessful` decorators we have around planning Behaviors in our example configs, since that's no longer needed now - ProRRT is deterministic.
I manually tested all the Objectives I'm changing here.
In the kinova config I had to update the waypoint names, because the ones we had didn't exist in that config.

remove RetryUntilSuccessful decorators around planning Behaviors

---

.gitmodules

Removed the Blender lighting and camera artifacts to render the UR20, UR3, and UR5 (not e) bots correctly.
Change the `picknik_ur_base_config config.yaml` to use the UR20 model and observe it looks normal.
Before:

fixed ur robot lighting issues

---

src/lab_sim/objectives/constrained_pick_and_place_subtree.xml
src/lab_sim/objectives/constrained_pick_place.xml
src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/move_to_joint_state.xml
src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/move_to_waypoint.xml

Exposes the `keep_orientation_link_names` port used in planning Behaviors via the `Move To Waypoint` subtree, so that it's more visibly exposed to users.
This is also referenced from the docs: https://github.com/PickNikRobotics/moveit_pro/pull/10632

plumb keep_orientation_link_names through subtrees

---

src/lab_sim/objectives/grasp_planning.xml

An example for https://github.com/PickNikRobotics/moveit_pro/pull/10469
Add a `Grasp Planning` Objective under the `Motion - Planning` category, in `lab_sim`.
Creates grasp poses to pick up a block, then sets up an MTC pipeline to find one that works and executes the grasp.
The plan is to use this example to show how to plan motion to a set of poses- see https://github.com/PickNikRobotics/moveit_pro/issues/9310 for context

add grasp planning example showcasing MTC batch IK

---

.pre-commit-config.yaml
Dockerfile
docker-compose.yaml

Now that [this](https://github.com/PickNikRobotics/moveit_pro/pull/10628) is merged, we can make this change.

Update docker files

---

src/lab_sim/description/picknik_ur.xacro
src/moveit_pro_kinova_configs/kinova_gen3_base_config/description/robotiq_2f_85_gripper.urdf

Depends on https://github.com/PickNikRobotics/picknik_accessories/pull/25
Closes https://github.com/PickNikRobotics/moveit_pro/issues/10823
Removes the d415.stl mesh we use directly in a couple of xacros and makes it a box instead, with another thin black box in the front for better visuals. This is how it looks like in `lab_sim`:

turn the realsense camera into a box

---

Dockerfile
docker-compose.yaml

This PR adds functional GPU Acceleration and GPU Inference to the example_ws for 7.0-7.3. This PR will become obsolete in 7.4, as a script will handle most of this, but customers are excited to use these features now.
For the Dockerfile changes, I directly integrate a known working TensorRT NVIDIA provided image for a few reasons:
1. The first time `docker pull` between these steps and the original `apt-update` [gdoc steps](https://docs.google.com/document/d/1Q4mdK88R2m8w8evjl74TgB01sS0DP8NI0wXzO_wlRHg/edit?usp=sharing) take about the same amount of time (the docker pull seemed faster). However, if you change anything in the Dockerfile above the `apt-update` steps, this whole process runs again. By integrating a separate image, as long as the image has not been pruned off the system, …

fix(user_ws): GPU inferencing and acceleration now properly working

---

src/lab_sim/config/config.yaml

The servo_controller and the JTC claim the same joints so they can't both be activated on startup.

lab_sim: don't activate servo controller at startup

---

src/hangar_sim/description/vacuum_urdf.xacro

Closes https://github.com/PickNikRobotics/moveit_pro/issues/10927
Tested by running hangar_sim and veryfing that:
* Pose jog arrows are aligned with camera view, i.e. left moves left
* Objective to move boxes still works

hangar_sim: rotate grasp link 180 deg

---

src/hangar_sim/params/nav2_params.yaml

Resolves PicknikRobotics/moveit_pro#11079
Navigating to various places in `hangar_sim` can cause the ridgeback to fail because it gets too close to obstacles.
The inflation radius was set to 0.3 meters, but the ridgeback documentation shows the largest width of the base is 0.96 meters https://clearpathrobotics.com/ridgeback-indoor-robot-platform/. 
I set the new inflation radius to 0.5 meters to give a little buffer. 
Send the robot from a place near the plane to a place where it will have to go around the plane using the "Navigate to Clicked Point" objective.

[11079] Ridgeback getting stuck on plane in `hangar_sim`

---

.pre-commit-config.yaml

Waypoints are written to the filesystem with no indent on sequences:
part of https://github.com/PickNikRobotics/moveit_pro/issues/11267
```
#waypoints
sequence:
- 1
- 2
- 3
sequence:
- 1
- 2
- 3
```
Both are valid yaml. this yamllint config change allows for either option as long as it is consistent within the same file.

Adjust yaml lint to allow for different sequence indent options

---

src/fanuc_sim/launch/agent_bridge.launch.xml
src/grinding_sim/launch/agent_bridge.launch.xml
src/hangar_sim/launch/agent_bridge.launch.xml
src/moveit_pro_kinova_configs/kinova_gen3_base_config/launch/agent_bridge.launch.xml
src/moveit_pro_kinova_configs/kinova_sim/launch/agent_bridge.launch.xml

This is a holdover from.. idk when, but rest_api.launch.xml is already invoked by the underlying agent_bridge.launch.xml in the core codebase, so this is definitely unnecessary.

Remove duplicate REST API launch from configs

---

Dockerfile

This is the default used by the wrapper script that calls this, so I've copied it here so that it stops throwing annoying warnings and should work out-of-box when building this Dockerfile without the launch script.
Closes PickNikRobotics/moveit_pro#11438.

Add valid default for container base image

---

src/hangar_sim/description/ur5e_ridgeback.xacro
src/hangar_sim/objectives/interpolate_to_joint_state.xml

Set the virtual linear joints range, in `hangar_sim`, to the size of the map, and fix joint jog by overriding `Interpolate to Joint State` to not list the robotiq controllers, which are not available in this config.
Closes https://github.com/PickNikRobotics/moveit_pro/issues/11537
To test, go to Teleoperate -> Joint Jog and move the slider of the linear joints. Check that the limits match roughly with the dimensions of the map. It should also move to the commanded value (assuming it's feasible)

fix linear joints range and joint teleoperate

---

src/hangar_sim/objectives/cartesian_draw_geometry_from_file.xml
src/hangar_sim/objectives/cartesian_path_with_collision_checking.xml
src/hangar_sim/objectives/cartesian_plan_simple_square.xml
src/hangar_sim/objectives/find_and_spray_plane.xml
src/hangar_sim/objectives/generate_grid_pattern_on_airplane.xml
src/hangar_sim/objectives/mobile_scan_and_plan.xml
src/hangar_sim/objectives/move_forward_2m.xml

Rename training Objectives to not contain "Solution - X"
Removes VisualizePath and  the execution Behavior at the end of `Cartesian Path with Collision Checking`
Closes https://github.com/PickNikRobotics/moveit_pro/issues/11623

Rename hangar_sim training objectives

---

src/moveit_pro_kinova_configs/kinova_sim/objectives/move_to_pose.xml

Not sure how this got out of sync, but this updates "Move to Pose" so that
- It doesn't unnecessarily call "RetrievePoseParameter" - the pose should be passed in via the port remap, not be expected to be retrieved from the UI in a Teleoperation context.
- Deletes some other behaviors that are no longer used in the "core" version of "Move to Pose"
For 8.0 we should decide if we are migrating all the configs to use the core objectives, including "Move to Pose", and make sure those objectives expose the needed port remaps, such as `planning_group_name` and `ik_frame`.
Run kinova_sim and space_satellite_sim and make sure the teleoperation modes like imarker still work.

Update Kinova 'Move To Pose' subtree to use remapped {target_pose} instead of calling 'RetrievePoseParameter' behavior

---

.dockerignore

When I was testing this on the v7.6.1 branch the build context went from 5.86GB down to 2.52.
Closes https://github.com/PickNikRobotics/moveit_pro/issues/11854

Make docker build context smaller

---

src/factory_sim/config/config.yaml
src/factory_sim/objectives/pick_up_tool.xml
src/factory_sim/objectives/place_tool_in_tool_holder.xml

Bug fixes from #224
- Make some subtrees non-runnable to prevent users from accidentally putting planning scene into an irrecoverable state.
- Do not launch mujoco viewer by default to better support low end hardware.

Make some subtrees non-runnable to prevent users from accidentally putting planning scene into an irrecoverable state.

---

.gitmodules
Dockerfile
src/moveit_pro_kinova_configs/kinova_gen3_base_config/config/moveit/pose_ik_speed.yaml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/CMakeLists.txt
src/moveit_pro_kinova_configs/kinova_gen3_site_config/config/config.yaml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/config/control/picknik_kinova_gen3.ros2_control.yaml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/config/initial_positions.yaml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/config/moveit/hard_joint_limits.yaml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/config/moveit/joint_limits.yaml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/config/moveit/kinova_gen3.srdf
src/moveit_pro_kinova_configs/kinova_gen3_site_config/config/moveit/kinova_gen3_servo.yaml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/description/kinova_gen3.xacro
src/moveit_pro_kinova_configs/kinova_gen3_site_config/launch/agent_bridge.launch.xml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/launch/cameras.launch.xml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/objectives/close_gripper.xml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/objectives/open_gripper.xml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/package.xml
src/moveit_pro_kinova_configs/kinova_gen3_site_config/waypoints/waypoints.yaml

Only remaining thing here is to figure out the Non-recoverable Fault on startup if it's not too big of a lift. Edit: should be resolved now

Add kinova gen3 site config

---

.github/workflows/ci.yaml

to fix CI failure [here](https://github.com/PickNikRobotics/moveit_pro_example_ws/actions/runs/14522246034/job/40745697844?pr=224)

Point to main hash for moveit_pro_lint

---

src/hangar_sim/objectives/ml_move_boxes_to_loading_zone.xml
src/lab_sim/objectives/ml_grasp_object_from_text_prompt.xml
src/lab_sim/objectives/ml_segment_image_from_text_prompt.xml
src/lab_sim/objectives/ml_segment_point_cloud_from_clicked_point.xml
src/lab_sim/objectives/ml_segment_point_cloud_from_text_prompt.xml

`hangar_sim`
Should the three objectives under `Perception - ML` also have `ML` prepended to them or was https://github.com/PickNikRobotics/moveit_pro/issues/11402 meant to only rename the ones that were already in the "Application" subcategory?
`lab_sim`

[11402] Add Application ML category

---

src/grinding_sim/objectives/move_to_pose.xml
src/grinding_sim/objectives/move_to_pose_imarker.xml
src/hangar_sim/objectives/move_to_pose.xml
src/lab_sim/objectives/request_teleoperation.xml

example_ws part of https://github.com/PickNikRobotics/moveit_pro/issues/12126.
Also requires https://github.com/PickNikRobotics/moveit_pro/pull/12127
Also fixed grinding_sim move_to_poses to be non-runnable.

Make MTC controllers pass-through, and change space to ; in controller list.

---

src/lab_sim/objectives/grasp_pose_tuning_with_april_tag.xml
src/lab_sim/objectives/grasp_pose_using_yaml.xml
src/lab_sim/objectives/relative_grasp_pose.yaml
src/lab_sim/objectives/take_picture_with_wrist_camera.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/pick_apriltag_labeled_object.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/teach_apriltag_grasp_offset.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/visual_servo_teach_reference.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/visual_servo_to_reference.xml

Replaces `LoadObjectiveParameters` + `TransformPoseFromYaml` by  `LoadPoseStampedFromYaml` and `TransformPoseWithPose` in all the example configs
Requires https://github.com/PickNikRobotics/moveit_pro/pull/12185
Closes https://github.com/PickNikRobotics/moveit_pro/issues/12160

Remove TransformPoseFromYaml

---

src/hangar_sim/config/config.yaml

There is a race condition between the JTC and the
platform_velocity_controller during startup since the JTC attempts to claim some joints exported by the platform_velocity_controller. Activating them both at statup causes the JTC to fail to activate sometimes.

Don't activate the JTC at startup in hangar_sim

---

docker-compose.yaml

It seems like in some version of docker-compose, the services must be followed by an empty curly bracket `{}` to be valid syntax or docker-compose will fail with an error message like `services must be a mapping`.

Make all docker-compose services mappings

---

src/lab_sim/objectives/apriltag_pick_object.xml
src/lab_sim/objectives/grasp_pose_using_yaml.xml
src/lab_sim/objectives/pick_and_place_example.xml
src/lab_sim/objectives/pick_april_tag_object_with_approval.xml
src/lab_sim/objectives/pick_from_pose.xml
src/lab_sim/objectives/pick_from_pose_with_approval.xml
src/lab_sim/objectives/pick_object.xml
src/lab_sim/objectives/place_at_pose.xml

* Simplify by adding the input pose to a vector in the subtree instead of requiring users to input a vector with a single pose.

Update Pick from Pose subtree and usages

---

src/hangar_sim/objectives/move_boxes_to_loading_zone_from_waypoint.xml

Removes the `link_padding` parameter from the `SetupMTCConnectWithTrajectory` action in the `move_boxes_to_loading_zone_from_waypoint.xml` file.

12505 Remove link padding parameter from SetupMTCConnectWithTrajectory from hangar_sim

---

src/hangar_sim/objectives/request_teleoperation.xml

`hangar_sim` needs link padding set to zero because the arm base link is very close to the base top plate, so adding padding makes those two links collide.
Depends on https://github.com/PickNikRobotics/moveit_pro/pull/12864

override link_padding to 0.0 in hangar sim teleop

---

src/factory_sim/objectives/inspect_convex_bowl.xml
src/factory_sim/objectives/pick_up_tool_from_holder.xml
src/factory_sim/objectives/place_tool_in_tool_holder.xml
src/factory_sim/objectives/retract.xml
src/hangar_sim/objectives/move_boxes_to_loading_zone_from_waypoint.xml
src/hangar_sim/objectives/move_to_pose_no_preview.xml
src/hangar_sim/objectives/request_teleoperation.xml
src/hangar_sim/objectives/solution_move_forward_2m.xml
src/lab_sim/objectives/add_poses_to_mtc_task.xml
src/lab_sim/objectives/grasp_planning.xml
src/lab_sim/objectives/ml_grasp_object_from_text_prompt.xml
src/lab_sim/objectives/move_along_square.xml
src/lab_sim/objectives/mpc_pose_tracking.xml
src/lab_sim/objectives/pick_from_pose.xml
src/lab_sim/objectives/pick_from_pose_with_approval.xml
src/lab_sim/objectives/place_at_pose.xml
src/lab_sim/objectives/place_at_pose_with_approval.xml
src/lab_sim/objectives/plan_move_to_pose.xml
src/moveit_pro_kinova_configs/kinova_sim/objectives/compliant_grasp_rafti_vfc.xml
src/moveit_pro_kinova_configs/space_satellite_sim_camera_cal/objectives/calibrate_camera_at_waypoint_-_tag_tfs.xml
src/moveit_pro_ur_configs/multi_arm_sim/objectives/multi_tip_pose_ik_example.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/inspect_surface.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/push_button.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/push_button_ml.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/retreat_to_initial_pose.xml

Updates configs to remove slashes from all controller names, e.g. `/joint_trajectory_controller` -> `joint_trajectory_controller`.
This makes it consistent everywhere and avoids potential issues with controller activation.
Slashed controller names are still accepted (after https://github.com/PickNikRobotics/moveit_pro/pull/12996) for backwards compatibility.
Closes https://github.com/PickNikRobotics/moveit_pro/issues/12962
Closes https://github.com/PickNikRobotics/moveit_pro/issues/12989

remove slashes from controller names

---

src/hangar_sim/objectives/compute_ik_plan_and_move.xml
src/hangar_sim/objectives/point-to-point_trajectory.xml
src/hangar_sim/waypoints/ur_waypoints.yaml

- Removes wheel joints from saved waypoints, since those are not needed and can trigger errors in some planning Behaviors that don't know what to do with the wheel actuators
- Adds a couple of training examples used in https://github.com/PickNikRobotics/moveit_pro/pull/13103

new hangar_sim training examples

---

Dockerfile

This was previously erroneously installed in core MoveIt Pro because we thought it was a meta package for "GPU support" in ONNX.
Turns out it's just a poorly-named CUDA-specific package.

Install ONNX CUDA runtime in GPU layer

---

src/moveit_pro_kinova_configs/space_satellite_sim_camera_cal/config/config.yaml
src/moveit_pro_kinova_configs/space_satellite_sim_camera_cal/objectives/calibrate_scene_camera.xml
src/moveit_pro_kinova_configs/space_satellite_sim_camera_cal/objectives/calibrate_servicer_camera.xml
src/moveit_pro_kinova_configs/space_satellite_sim_camera_cal/objectives/calibrate_servicer_camera_-_tag_tfs.xml

Closes https://github.com/PickNikRobotics/moveit_pro/issues/13351.
space_satellite_sim objectives won't work, so overwrite space_satellite_sim Objectives with space_satellite_sim_camera_cal Objectives in config so only the Calibration Objectives are available.

Only have calibration objectives, and favorite them.

---

src/lab_sim/objectives/mpc_pose_tracking.xml

Remove leading slash from controller name in MPC Pose Tracking

---

.dockerignore

`log` wasn't ignored in the build context and was causing cache busts.

Fix caching of dependency steps in Docker build

---

src/hangar_sim/objectives/move_boxes_to_loading_zone_from_waypoint.xml
src/hangar_sim/objectives/segment_image_from_point.xml
src/hangar_sim/objectives/segment_point_cloud_from_clicked_point.xml
src/lab_sim/objectives/get_candidate_grasps_subtree.xml
src/lab_sim/objectives/ml_auto_grasp_object_from_clicked_point.xml
src/lab_sim/objectives/ml_segment_point_cloud_from_clicked_point.xml
src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/segment_image_from_point_subtree.xml

https://github.com/PickNikRobotics/moveit_pro_example_ws/pull/387 accidentally pointed the model package for SAM2 and L2G to `moveit_pro_clipseg`, which does not contain weights for those models. Changing them back to `lab_sim`

13833 Change weights package for SAM2 and L2G back to lab_sim

---

src/moveit_pro_kinova_configs/space_satellite_sim/objectives/close_gripper.xml
src/moveit_pro_kinova_configs/space_satellite_sim/objectives/grapple_moving_satellite_via_fiducial_tracking.xml
src/moveit_pro_kinova_configs/space_satellite_sim/objectives/open_gripper.xml

https://github.com/PickNikRobotics/moveit_pro/issues/14362
I reverted the names of "Open Gripper" and Close "Gripper" objectives, including their use in the objective "Grapple Moving Satellite via Fiducial Tracking"
If you work in dev mode, remember to launch 
`ros2 launch space_satellite_sim agent_bridge.launch.xml`
instead of
`agent_bridge.app`
Check that the gripper open and close in teleoperation mode and run the objective "Grapple Moving Satellite via Fiducial Tracking".

Reverted change for gripper objectives in satellite_sim.

---

src/moveit_pro_ur_configs/mock_sim/config/config.yaml
src/moveit_pro_ur_configs/mock_sim/config/control/picknik_ur.ros2_control.yaml

when running mock_sim example the admitance controller is unstable. the reason is that `/force_torque_sensor_broadcaster/wrench` is publishing all NaNs .
this PR removes the FTS sensor from ros2_control and as a result admitance controller is  working as expected
Closes https://github.com/PickNikRobotics/moveit_pro/issues/13267

ignores the fts sensor feedback which is publishing nans
