PickNikRobotics/moveit_pro_example_ws

src/fanuc_sim/CMakeLists.txt
src/fanuc_sim/description/scene.xml
src/fanuc_sim/package.xml

patching fanuc

---

src/example_behaviors/CMakeLists.txt
src/example_behaviors/include/example_behaviors/example_add_two_ints_service_client.hpp
src/example_behaviors/include/example_behaviors/example_convert_mtc_solution_to_joint_trajectory.hpp
src/example_behaviors/include/example_behaviors/example_delayed_message.hpp
src/example_behaviors/include/example_behaviors/example_fibonacci_action_client.hpp
src/example_behaviors/include/example_behaviors/example_get_string_from_topic.hpp
src/example_behaviors/include/example_behaviors/example_hello_world.hpp
src/example_behaviors/include/example_behaviors/example_ndt_registration.hpp
src/example_behaviors/include/example_behaviors/example_publish_color_rgba.hpp
src/example_behaviors/include/example_behaviors/example_ransac_registration.hpp
src/example_behaviors/include/example_behaviors/example_setup_mtc_pick_from_pose.hpp
src/example_behaviors/include/example_behaviors/example_setup_mtc_place_from_pose.hpp
src/example_behaviors/include/example_behaviors/example_setup_mtc_wave_hand.hpp
src/example_behaviors/src/example_add_two_ints_service_client.cpp
src/example_behaviors/src/example_convert_mtc_solution_to_joint_trajectory.cpp
src/example_behaviors/src/example_delayed_message.cpp
src/example_behaviors/src/example_fibonacci_action_client.cpp
src/example_behaviors/src/example_get_string_from_topic.cpp
src/example_behaviors/src/example_hello_world.cpp
src/example_behaviors/src/example_ndt_registration.cpp
src/example_behaviors/src/example_publish_color_rgba.cpp
src/example_behaviors/src/example_ransac_registration.cpp
src/example_behaviors/src/example_setup_mtc_pick_from_pose.cpp
src/example_behaviors/src/example_setup_mtc_place_from_pose.cpp
src/example_behaviors/src/example_setup_mtc_wave_hand.cpp
src/example_behaviors/src/register_behaviors.cpp
src/example_behaviors/test/test_behavior_plugins.cpp

Add 'Example' prefix to all behavior classnames and filenames in example_behaviors repository

---

src/example_behaviors/src/example_add_two_ints_service_client.cpp
src/example_behaviors/src/example_delayed_message.cpp
src/example_behaviors/src/example_fibonacci_action_client.cpp
src/example_behaviors/src/example_get_string_from_topic.cpp
src/example_behaviors/src/example_hello_world.cpp
src/example_behaviors/src/example_publish_color_rgba.cpp
src/example_behaviors/src/example_setup_mtc_pick_from_pose.cpp
src/example_behaviors/src/example_setup_mtc_place_from_pose.cpp
src/example_behaviors/src/example_setup_mtc_wave_hand.cpp
src/lab_sim/objectives/3_waypoint_pick_and_place.xml
src/lab_sim/objectives/constrained_pick_place.xml
src/lab_sim/objectives/cycle_between_waypoints.xml
src/lab_sim/objectives/get_april_tag_pose_from_image.xml
src/lab_sim/objectives/joint_diagnostic.xml
src/lab_sim/objectives/load_and_execute_joint_trajectory.xml
src/lab_sim/objectives/look_at_table.xml
src/lab_sim/objectives/move_with_velocity_and_force.xml
src/lab_sim/objectives/pick_and_place_example.xml
src/lab_sim/objectives/pick_april_tag_object_with_approval.xml
src/lab_sim/objectives/pick_object.xml
src/lab_sim/objectives/pick_up_cube.xml
src/lab_sim/objectives/place_first_object_in_vector.xml
src/lab_sim/objectives/place_object.xml
src/lab_sim/objectives/plan_move_to_pose.xml
src/lab_sim/objectives/plan_to_pose.xml
src/lab_sim/objectives/register_cad_part.xml
src/lab_sim/objectives/take_snap.xml
src/lab_sim/objectives/visualize_pose.xml
src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/clear_snapshot.xml
src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/close_gripper.xml

updated categories to be the established ones and added to objectives missing them

fix(workspace): categories readded for lab_sim

---

docker-compose.yaml

Reverts PickNikRobotics/moveit_pro_example_ws#34

Revert "Remove `docker-compose.yaml`"

---

src/moveit_pro_ur_configs/bring_it_sim/waypoints/ur_waypoints.yaml

Add waypoints

---

src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/move_to_joint_state.xml

More detailed Objective description

---

src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/move_to_pose.xml

Update Objective description

---

src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/move_to_waypoint.xml

Expand description of objective

---

src/lab_sim/objectives/pick_first_object_in_vector.xml
src/lab_sim/objectives/place_first_object_in_vector.xml
src/lab_sim/objectives/plan_to_pose.xml
src/lab_sim/objectives/run_sam2_onnx.xml
src/moveit_pro_mobile_manipulation/picknik_ur_mobile_config/objectives/pick_first_object_in_vector.xml
src/moveit_pro_mobile_manipulation/picknik_ur_mobile_config/objectives/pick_object.xml
src/moveit_pro_ur_configs/arm_on_rail_sim/objectives/pick_first_object_in_vector.xml
src/moveit_pro_ur_configs/arm_on_rail_sim/objectives/place_first_object_in_vector.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/close_cabinet_door.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/detect_door_graspable_object.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/detect_fixed_handle_graspable_object.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/detect_hinge_line_segment.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/detect_lever_handle_line_segment.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/inspect_surface.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/looping_pick_and_place_object.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/open_cabinet_door.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/open_door_fixed_handle_ml.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/open_door_lever_handle_ml.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/open_lever_handle_door.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/pick_object.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/pick_place_object.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/push_button.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/push_button_ml.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/sam_pick_object.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/teach_apriltag_grasp_offset.xml

```
sed -i -e 's/ForEach\w\+"/ForEach"/g' src/**/*.xml
```

Find and replace everything ForEach\w+ to just ForEach

---

src/lab_sim/objectives/constrained_pick_place.xml
src/lab_sim/objectives/pick_and_place_example.xml
src/lab_sim/objectives/plan_and_save_trajectory.xml
src/lab_sim/objectives/register_cad_part.xml
src/lab_sim/objectives/run_sam2_onnx.xml
src/lab_sim/objectives/save_and_execute_a_trajectory_from_disk.xml
src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/clear_snapshot.xml
src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/close_gripper.xml

Closes PickNikRobotics/moveit_studio#9987 with PickNikRobotics/moveit_studio#10098.

fix: added subcategories to the missing objectives

---

src/moveit_pro_mobile_manipulation/picknik_ur_mobile_config/config/moveit/picknik_ur.srdf

Closes https://github.com/PickNikRobotics/moveit_pro/issues/10339

update ACM for links that don't collide

---

src/lab_sim/objectives/_scan_scene.xml
src/lab_sim/objectives/constrained_pick_and_place_subtree.xml
src/lab_sim/objectives/segment_point_cloud_from_clicked_point.xml

Closes https://github.com/PickNikRobotics/moveit_pro/issues/10358

Objective categories

---

src/fanuc_sim/objectives/clear_snapshot.xml
src/lab_sim/objectives/add_waypoints_to_mtc_task.xml
src/lab_sim/objectives/create_pose_vector.xml
src/lab_sim/objectives/load_mesh_as_green_poincloud.xml
src/lab_sim/objectives/load_mesh_as_red_pointcloud.xml
src/lab_sim/objectives/pick_first_object_in_vector.xml
src/lab_sim/objectives/register_cad_part.xml
src/lab_sim/objectives/run_sam2_onnx.xml
src/moveit_pro_kinova_configs/kinova_gen3_base_config/objectives/clear_snapshot.xml
src/moveit_pro_kinova_configs/kinova_gen3_base_config/objectives/close_gripper.xml
src/moveit_pro_kinova_configs/kinova_gen3_mujoco_config/objectives/clear_snapshot.xml
src/moveit_pro_kinova_configs/kinova_gen3_mujoco_config/objectives/close_gripper.xml
src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/clear_snapshot.xml
src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/close_gripper.xml
src/moveit_pro_ur_configs/picknik_ur_multi_arm_config/objectives/clear_snapshot.xml

Closes PickNikRobotics/moveit_pro#10565, PickNikRobotics/moveit_pro#10563, and PickNikRobotics/moveit_pro#10511
Please make sure we cut this branch back to main, I think I've fixed the Clear Snapshot bug 3 separate times now :pensive:

fix: updated categories and objectives

---

src/lab_sim/objectives/constrained_pick_and_place_subtree.xml

quick fix to add a description and change subcategory to address and close PickNikRobotics/moveit_pro#10765

fix(lab_sim): description and category for constrained pick and place

---

docker-compose.yaml

hello. **please do not commit this back to main** as this will be unnecessary to have in the docker-compose.yaml once the script comes out in 7.4.0. but uncommenting these lines should fix the issue with NVIDIA GPUs
thank you

fix(temp): added to drivers to make mujoco run smoother

---

src/lab_sim/config/config.yaml
src/lab_sim/config/moveit/sensors_3d.yaml
src/lab_sim/objectives/wrist_snap.xml

See https://github.com/PickNikRobotics/moveit_pro/issues/10644 for context.

Revert octomap change

---

src/grinding_sim/objectives/save_tool_pose_yaml.xml

I'm referencing this in the Cartesian planning docs

Add Save Tool Pose Yaml objective to grinding_sim

---

src/grinding_sim/description/scene.xml
src/grinding_sim/description/ur20.urdf

This needs a submodule update for picknik_accessories

Add color to mujoco tool

---

src/lab_sim/config/control/picknik_ur.ros2_control.yaml

Corresponds to https://github.com/PickNikRobotics/moveit_pro/pull/10961.
Pulled code comments from tutorial code snippet into example_ws .yaml file.

Docs vfc params comments

---

src/lab_sim/objectives/request_teleoperation.xml

Closes https://github.com/PickNikRobotics/moveit_pro/issues/11029

provides request teleoperation subtree with a default value for `user_interaction_print`

---

src/lab_sim/description/picknik_ur.xacro

Closes https://github.com/PickNikRobotics/moveit_pro/issues/10375

remove table from urdf

---

src/moveit_pro_kinova_configs/space_satellite_sim/config/config.yaml

resolves https://github.com/PickNikRobotics/moveit_pro/issues/11080

Don't launch mujoco viewer by default in space_satellite_sim

---

Dockerfile

quick change on where we get our nvidia stuff from to make it faster

fix: nvidia download faster from apt

---

src/lab_sim/objectives/grasp_object_from_text_prompt.xml

Updates `Grasp Object From Text Prompt` to use the batch IK stage, instead of iterating through the poses one by one.
Also to use `Close Gripper`, which has a `ForceSuccess` decorator
Closes https://github.com/PickNikRobotics/moveit_pro/issues/11153

update Grasp Object From Text Prompt to use batch IK

---

src/lab_sim/objectives/grasp_object_from_text_prompt.xml
src/lab_sim/objectives/grasp_pose_tuning_with_april_tag.xml
src/lab_sim/objectives/grasp_pose_using_yaml.xml
src/lab_sim/objectives/pick_and_place_example.xml
src/lab_sim/objectives/pick_up_cube.xml
src/lab_sim/objectives/segment_point_cloud_from_clicked_point.xml

Resolves https://github.com/PickNikRobotics/moveit_pro/issues/11276

Update Objective descriptions for the `lab_sim` config

---

Dockerfile

remove all the unnecessary stuff now that https://github.com/PickNikRobotics/moveit_pro/pull/11329 exists

fix(docker): build kit volume mounting

---

src/moveit_pro_ur_configs/mock_sim/objectives/joint_diagnostic.xml

Closes https://github.com/PickNikRobotics/moveit_pro/issues/11313

don't use link padding in joint diagnostic Objective

---

colcon-defaults.yaml

Closes https://github.com/PickNikRobotics/moveit_pro/issues/11104

fix: properly override binary packages with our source versions

---

src/example_behaviors/CMakeLists.txt
src/example_behaviors/include/example_behaviors/example_create_string_msg.hpp
src/example_behaviors/src/example_create_string_msg.cpp
src/example_behaviors/src/register_behaviors.cpp

Will convert from draft once https://github.com/PickNikRobotics/moveit_pro/pull/11174 goes in
Partially resolves https://github.com/PickNikRobotics/moveit_pro/issues/10326

Add json serialization example for documentation to reference

---

src/moveit_pro_ur_configs/multi_arm_sim/objectives/multi_tip_ik_example.xml

Example for https://github.com/PickNikRobotics/moveit_pro/pull/11246

add multi-tip IK example

---

src/hangar_sim/config/moveit/joint_limits.yaml
src/hangar_sim/objectives/get_point_cloud_center_pose.xml
src/hangar_sim/objectives/move_to_a_stampedpose.xml
src/hangar_sim/objectives/move_to_arm_upright.xml
src/hangar_sim/objectives/move_to_look_at_plane.xml
src/hangar_sim/objectives/picknik.yaml
src/hangar_sim/objectives/solution_-_find_and_spray_plane.xml
src/hangar_sim/objectives/solution_draw_picknik.xml
src/hangar_sim/objectives/solution_draw_square.xml
src/hangar_sim/objectives/solution_follow_path.xml
src/hangar_sim/objectives/solution_generate_coverage_path.xml
src/hangar_sim/objectives/solution_move_forward_2m.xml
src/hangar_sim/objectives/solution_spray_plane.xml
src/hangar_sim/waypoints/ur_waypoints.yaml

Adds waypoints and objectives for training in hangar_sim

Hangar sim training

---

src/lab_sim/objectives/plan_and_save_trajectory.xml

Makes it match with Load and Execute Trajectory
Closes PickNikRobotics/moveit_pro#11568

Update category of Plan and Save Trajectory

---

src/hangar_sim/objectives/get_point_cloud_center_pose.xml

It cannot run without input so should not be runnable.

Make "Get Point Cloud Center Pose" subtree only

---

docker-compose.yaml

closes example_ws side of this issue: https://github.com/PickNikRobotics/moveit_pro/issues/11878

Delete obsolete nvidia commented lines. It's now handled automatically.

---

src/lab_sim/objectives/grasp_object_from_text_prompt.xml
src/lab_sim/objectives/grasp_planning.xml
src/lab_sim/objectives/pick_from_pose.xml
src/lab_sim/objectives/pick_from_pose_with_approval.xml
src/lab_sim/objectives/place_at_pose.xml
src/lab_sim/objectives/place_at_pose_with_approval.xml
src/lab_sim/objectives/plan_move_to_pose.xml
src/lab_sim/objectives/plan_to_pose.xml
src/moveit_pro_kinova_configs/kinova_sim/objectives/compliant_grasp_rafti_vfc.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/looping_pick_and_place_object.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/pick_object.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/pick_place_object.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/sam_pick_object.xml

Requires https://github.com/PickNikRobotics/moveit_pro/pull/11946

Update InitializeMTCTask to take controller_names as vector

---

src/moveit_pro_ur_configs/picknik_ur_base_config/objectives/segment_image_from_no_negative_text_prompt_subtree.xml

Uses bounding box feature added to `PublishMask2D` in (https://github.com/PickNikRobotics/moveit_pro/pull/11409)
to add the clipseg prompts to the "Segment Image from Text Prompt" and "Segment Point Cloud from Text Prompt"

[11559] Add clipseg prompt to bounding boxes of "Segment Image from Text Prompt"

---

src/lab_sim/objectives/take_picture_with_wrist_camera.xml

Follow-up for https://github.com/PickNikRobotics/moveit_pro_example_ws/pull/265

Remove LoadObjectiveParameters from Take Wrist Camera Image

---

src/lab_sim/objectives/add_poses_to_mtc_task.xml
src/lab_sim/objectives/force_relaxation.xml
src/lab_sim/objectives/grasp_planning.xml

- renames "Add Poses to MTC Task" objective file to be consistent with objective name
- makes "Add Poses to MTC Task" a subtree only objective
- makes "Force Relaxation" a subtree only objective
- Changes a planner interface in "Grasp Planning" objective

Make a couple objectives "subtree only" and other slight changes

---

src/moveit_pro_ur_configs/multi_arm_sim/config/config.yaml
src/moveit_pro_ur_configs/multi_arm_sim/objectives/request_teleoperation.xml

Closes https://github.com/PickNikRobotics/moveit_pro/issues/12210.
Note: this fixes the click slider and drag for Joint jog, but the +/- buttons are still inoperable.

Added controllers for click and drag jointJog slider.

---

src/factory_sim/objectives/plan_and_execute_with_orientation_samples.xml
src/lab_sim/objectives/grasp_planning.xml
src/lab_sim/objectives/ml_grasp_object_from_text_prompt.xml
src/lab_sim/objectives/pick_from_pose.xml
src/lab_sim/objectives/pick_from_pose_with_approval.xml
src/lab_sim/objectives/place_at_pose.xml
src/lab_sim/objectives/place_at_pose_with_approval.xml
src/moveit_pro_ur_configs/picknik_ur_site_config/objectives/pick_object.xml

Need https://github.com/PickNikRobotics/moveit_pro/pull/12227 to go in first

Add ik_group port to SetupMTCBatchPoseIK

---

src/lab_sim/objectives/constrained_pick_place.xml
src/lab_sim/objectives/record_square_trajectory.xml
src/lab_sim/waypoints/ur_waypoints.yaml

As you pointed out yesterday, flask is the correct term here.
For other reviewers as reference:

Use correct term for picked objects: beaker -> flask

---

src/hangar_sim/objectives/box_picking_vacuum_config.yaml
src/hangar_sim/objectives/move_boxes_to_loading_zone_from_waypoint.xml
src/lab_sim/objectives/grasp_planning.xml

Depends on https://github.com/PickNikRobotics/moveit_pro/pull/12149, https://github.com/PickNikRobotics/moveit_pro/pull/12227 and https://github.com/PickNikRobotics/moveit_pro/pull/12418
Closes [#12159](https://github.com/PickNikRobotics/moveit_pro/issues/12159)

Replace LoadObjectiveParameters and dependend Behaviors in hangar_sim Move Boxes objective

---

src/factory_sim/config/config.yaml
src/factory_sim/description/box-welds.xml
src/factory_sim/description/inspection_tool.urdf
src/factory_sim/description/inspection_tool.xml
src/factory_sim/description/picknik_fanuc.xacro
src/factory_sim/description/scene.xml
src/factory_sim/description/suction_tool.urdf
src/factory_sim/description/suction_tool.xml
src/factory_sim/objectives/automated_pickup_tool_subtree.xml
src/factory_sim/objectives/automated_return_held_tool.xml
src/factory_sim/objectives/automated_return_tool_subtree.xml
src/factory_sim/objectives/automated_tool_changing_example.xml
src/factory_sim/objectives/automated_tool_changing_example_subtree.xml
src/factory_sim/objectives/detach_and_remove_tool.xml
src/factory_sim/objectives/inspect_convex_bowl.xml
src/factory_sim/objectives/pick_up_tool_from_holder.xml
src/factory_sim/objectives/place_tool_in_tool_holder.xml
src/factory_sim/objectives/remove_tools_from_planningscene.xml
src/factory_sim/objectives/reset_planning_scene.xml
src/factory_sim/objectives/setup_initial_planning_scene.xml
src/factory_sim/objectives/tool_attachment_example.xml
src/factory_sim/waypoints/waypoints.yaml

Resolves https://github.com/PickNikRobotics/moveit_pro/issues/12184
To test:
Run all of the Objectives on the sidebar

Add new tool changing Objectives

---

src/hangar_sim/objectives/interpolate_to_joint_state.xml
src/hangar_sim/objectives/move_to_a_stampedpose.xml
src/hangar_sim/objectives/segment_image_from_text_prompt.xml

Changed these to be subtree only

Fix runnable state for Move to a StampedPose and Interpolate to Joint State in hangar_sim

---

.github/workflows/ci.yaml
src/factory_sim/config/config.yaml
src/factory_sim/description/box-welds.xml
src/factory_sim/description/inspection_tool.urdf
src/factory_sim/description/inspection_tool.xml
src/factory_sim/description/picknik_fanuc.xacro
src/factory_sim/description/scene.xml
src/factory_sim/description/suction_tool.urdf
src/factory_sim/description/suction_tool.xml
src/factory_sim/objectives/automated_pickup_tool_subtree.xml
src/factory_sim/objectives/automated_return_held_tool.xml
src/factory_sim/objectives/automated_return_tool_subtree.xml
src/factory_sim/objectives/automated_tool_changing_example.xml
src/factory_sim/objectives/automated_tool_changing_example_subtree.xml
src/factory_sim/objectives/detach_and_remove_tool.xml
src/factory_sim/objectives/inspect_convex_bowl.xml
src/factory_sim/objectives/pick_up_tool_from_holder.xml
src/factory_sim/objectives/place_tool_in_tool_holder.xml
src/factory_sim/objectives/remove_tools_from_planningscene.xml
src/factory_sim/objectives/reset_planning_scene.xml
src/factory_sim/objectives/setup_initial_planning_scene.xml
src/factory_sim/objectives/tool_attachment_example.xml
src/factory_sim/waypoints/waypoints.yaml
src/lab_sim/CMakeLists.txt
src/lab_sim/objectives/load_mesh_as_green_poincloud.xml
src/lab_sim/objectives/load_mesh_as_red_pointcloud.xml
src/lab_sim/objectives/wrist_snap.xml
src/lab_sim/test/objectives_integration_test.py

Merge 8.0 8.1

---

src/lab_sim/objectives/ml_segment_point_cloud_from_text_prompt.xml

Bad description

---

src/lab_sim/description/picknik_ur.xacro

See the [comparison in picknik_accessories](https://github.com/PickNikRobotics/picknik_accessories/pull/30), but now you should be able to grab the bottle by it's cap without gripper failures

Update lab_sim bottle shape to make it more graspable

---

src/lab_sim/description/simple_scene.xml
src/lab_sim/objectives/mpc_pose_tracking.xml

This example of using the MPC behavior was requested during the review for the release notes here https://github.com/PickNikRobotics/moveit_pro/pull/12702

Add MPC pose tracking example

---

src/moveit_pro_franka_configs/franka_mujoco_config/CMakeLists.txt
src/moveit_pro_franka_configs/franka_mujoco_config/config/config.yaml
src/moveit_pro_franka_configs/franka_mujoco_config/objectives/moveitpro_loves_franka.yaml
src/moveit_pro_franka_configs/franka_mujoco_config/objectives/wipe_text.xml
src/moveit_pro_franka_configs/franka_mujoco_config/objectives/write_text.xml
src/moveit_pro_franka_configs/franka_mujoco_config/objectives/writing_demo.xml

I added the writing behavior into the mujoco config. Only the subtree works because there is no gripper configured.

Write a text.

---

src/lab_sim/objectives/add_point_cloud_to_vector.xml
src/lab_sim/objectives/fuse_multiple_views.xml
src/lab_sim/test/objectives_integration_test.py
src/lab_sim/waypoints/ur_waypoints.yaml

Adds a `Fuse Multiple Views` Perception example, using the `MergePointClouds` Behavior
Closes https://github.com/PickNikRobotics/moveit_pro/issues/12918
[Screencast from 06-19-2025 10:13:57 AM.webm](https://github.com/user-attachments/assets/54da3435-5d95-4bcd-9ddf-00b13cf9f1a6)

add example to fuse point clouds

---

src/moveit_pro_kinova_configs/space_satellite_sim/config/config.yaml

i made you read this description for no reason haha

fix: turn off the viewer in space satellite sim

---

src/grinding_sim/description/scene.xml

Fixes https://github.com/PickNikRobotics/moveit_pro/issues/13630

lower kp gains for distal actuators in grinding sim

---

src/moveit_pro_kinova_configs/kinova_sim/objectives/april_tag_object_registration.xml
src/moveit_pro_kinova_configs/kinova_sim/objectives/write_picknik.xml

Also adds some visualization of the target poses and paths.
Closes https://github.com/PickNikRobotics/moveit_pro/issues/13642
Closes https://github.com/PickNikRobotics/moveit_pro/issues/13644

add tip offset to account for the special fingers
